# Generated by Django 4.0.2 on 2022-02-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seriados', '0003_alter_episodio_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reviewepisodio',
            name='episodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.episodio', verbose_name='Episódio'),
        ),
        migrations.AlterField(
            model_name='reviewepisodio',
            name='nota',
            field=models.CharField(choices=[('A', 'Excelente'), ('B', 'Bom'), ('C', 'Ruim')], default='B', max_length=1, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='reviewepisodio',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.revisor', verbose_name='Revisor'),
        ),
        migrations.AlterField(
            model_name='revisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Revisores'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.serie', verbose_name='Série'),
        ),
    ]
