# Generated by Django 4.0.2 on 2022-02-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seriados', '0004_alter_episodio_data_alter_reviewepisodio_episodio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
    ]
