# Generated by Django 4.0.2 on 2022-02-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seriados', '0005_alter_serie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={'verbose_name': 'Episódio', 'verbose_name_plural': 'Episódios'},
        ),
        migrations.AlterModelOptions(
            name='reviewepisodio',
            options={'verbose_name': 'Review Episódio', 'verbose_name_plural': 'Reviews Episódios'},
        ),
        migrations.AlterModelOptions(
            name='revisor',
            options={'verbose_name': 'Revisor', 'verbose_name_plural': 'Revisores'},
        ),
        migrations.AlterModelOptions(
            name='temporada',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
    ]
