# Generated by Django 4.0.2 on 2022-03-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seriados', '0006_alter_episodio_options_alter_reviewepisodio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=100, verbose_name='Titulo')),
                ('url', models.SlugField(max_length=100, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('data', models.DateField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
